<?php

/* custom routes generated by CRUD */

Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('companies', ['as'=> 'companies.index', 'uses' => 'CompanyController@index']);
Route::post('companies', ['as'=> 'companies.store', 'uses' => 'CompanyController@store']);
Route::get('companies/create', ['as'=> 'companies.create', 'uses' => 'CompanyController@create']);
Route::put('companies/{companies}', ['as'=> 'companies.update', 'uses' => 'CompanyController@update']);
Route::patch('companies/{companies}', ['as'=> 'companies.update', 'uses' => 'CompanyController@update']);
Route::get('companies/{id}/delete', array('as' => 'companies.delete', 'uses' => 'CompanyController@getDelete'));
Route::get('companies/{id}/confirm-delete', array('as' => 'companies.confirm-delete', 'uses' => 'CompanyController@getModalDelete'));
Route::get('companies/{companies}', ['as'=> 'companies.show', 'uses' => 'CompanyController@show']);
Route::get('companies/{companies}/edit', ['as'=> 'companies.edit', 'uses' => 'CompanyController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('contactCompanies', ['as'=> 'contactCompanies.index', 'uses' => 'ContactCompanyController@index']);
Route::post('contactCompanies', ['as'=> 'contactCompanies.store', 'uses' => 'ContactCompanyController@store']);
Route::get('contactCompanies/create', ['as'=> 'contactCompanies.create', 'uses' => 'ContactCompanyController@create']);
Route::put('contactCompanies/{contactCompanies}', ['as'=> 'contactCompanies.update', 'uses' => 'ContactCompanyController@update']);
Route::patch('contactCompanies/{contactCompanies}', ['as'=> 'contactCompanies.update', 'uses' => 'ContactCompanyController@update']);
Route::get('contactCompanies/{id}/delete', array('as' => 'contactCompanies.delete', 'uses' => 'ContactCompanyController@getDelete'));
Route::get('contactCompanies/{id}/confirm-delete', array('as' => 'contactCompanies.confirm-delete', 'uses' => 'ContactCompanyController@getModalDelete'));
Route::get('contactCompanies/{contactCompanies}', ['as'=> 'contactCompanies.show', 'uses' => 'ContactCompanyController@show']);
Route::get('contactCompanies/{contactCompanies}/edit', ['as'=> 'contactCompanies.edit', 'uses' => 'ContactCompanyController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('departmentCompanies', ['as'=> 'departmentCompanies.index', 'uses' => 'DepartmentCompanyController@index']);
Route::post('departmentCompanies', ['as'=> 'departmentCompanies.store', 'uses' => 'DepartmentCompanyController@store']);
Route::get('departmentCompanies/create', ['as'=> 'departmentCompanies.create', 'uses' => 'DepartmentCompanyController@create']);
Route::put('departmentCompanies/{departmentCompanies}', ['as'=> 'departmentCompanies.update', 'uses' => 'DepartmentCompanyController@update']);
Route::patch('departmentCompanies/{departmentCompanies}', ['as'=> 'departmentCompanies.update', 'uses' => 'DepartmentCompanyController@update']);
Route::get('departmentCompanies/{id}/delete', array('as' => 'departmentCompanies.delete', 'uses' => 'DepartmentCompanyController@getDelete'));
Route::get('departmentCompanies/{id}/confirm-delete', array('as' => 'departmentCompanies.confirm-delete', 'uses' => 'DepartmentCompanyController@getModalDelete'));
Route::get('departmentCompanies/{departmentCompanies}', ['as'=> 'departmentCompanies.show', 'uses' => 'DepartmentCompanyController@show']);
Route::get('departmentCompanies/{departmentCompanies}/edit', ['as'=> 'departmentCompanies.edit', 'uses' => 'DepartmentCompanyController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('analyses', ['as'=> 'analyses.index', 'uses' => 'AnalysisController@index']);
Route::post('analyses', ['as'=> 'analyses.store', 'uses' => 'AnalysisController@store']);
Route::get('analyses/create', ['as'=> 'analyses.create', 'uses' => 'AnalysisController@create']);
Route::put('analyses/{analyses}', ['as'=> 'analyses.update', 'uses' => 'AnalysisController@update']);
Route::patch('analyses/{analyses}', ['as'=> 'analyses.update', 'uses' => 'AnalysisController@update']);
Route::get('analyses/{id}/delete', array('as' => 'analyses.delete', 'uses' => 'AnalysisController@getDelete'));
Route::get('analyses/{id}/confirm-delete', array('as' => 'analyses.confirm-delete', 'uses' => 'AnalysisController@getModalDelete'));
Route::get('analyses/{analyses}', ['as'=> 'analyses.show', 'uses' => 'AnalysisController@show']);
Route::get('analyses/{analyses}/edit', ['as'=> 'analyses.edit', 'uses' => 'AnalysisController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('rSLS', ['as'=> 'rSLS.index', 'uses' => 'RSLController@index']);
Route::post('rSLS', ['as'=> 'rSLS.store', 'uses' => 'RSLController@store']);
Route::get('rSLS/create', ['as'=> 'rSLS.create', 'uses' => 'RSLController@create']);
Route::put('rSLS/{rSLS}', ['as'=> 'rSLS.update', 'uses' => 'RSLController@update']);
Route::patch('rSLS/{rSLS}', ['as'=> 'rSLS.update', 'uses' => 'RSLController@update']);
Route::get('rSLS/{id}/delete', array('as' => 'rSLS.delete', 'uses' => 'RSLController@getDelete'));
Route::get('rSLS/{id}/confirm-delete', array('as' => 'rSLS.confirm-delete', 'uses' => 'RSLController@getModalDelete'));
Route::get('rSLS/{rSLS}', ['as'=> 'rSLS.show', 'uses' => 'RSLController@show']);
Route::get('rSLS/{rSLS}/edit', ['as'=> 'rSLS.edit', 'uses' => 'RSLController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('prodSpecs', ['as'=> 'prodSpecs.index', 'uses' => 'ProdSpecController@index']);
Route::post('prodSpecs', ['as'=> 'prodSpecs.store', 'uses' => 'ProdSpecController@store']);
Route::get('prodSpecs/create', ['as'=> 'prodSpecs.create', 'uses' => 'ProdSpecController@create']);
Route::put('prodSpecs/{prodSpecs}', ['as'=> 'prodSpecs.update', 'uses' => 'ProdSpecController@update']);
Route::patch('prodSpecs/{prodSpecs}', ['as'=> 'prodSpecs.update', 'uses' => 'ProdSpecController@update']);
Route::get('prodSpecs/{id}/delete', array('as' => 'prodSpecs.delete', 'uses' => 'ProdSpecController@getDelete'));
Route::get('prodSpecs/{id}/confirm-delete', array('as' => 'prodSpecs.confirm-delete', 'uses' => 'ProdSpecController@getModalDelete'));
Route::get('prodSpecs/{prodSpecs}', ['as'=> 'prodSpecs.show', 'uses' => 'ProdSpecController@show']);
Route::get('prodSpecs/{prodSpecs}/edit', ['as'=> 'prodSpecs.edit', 'uses' => 'ProdSpecController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('reports', ['as'=> 'reports.index', 'uses' => 'ReportController@index']);
Route::post('reports', ['as'=> 'reports.store', 'uses' => 'ReportController@store']);
Route::get('reports/create', ['as'=> 'reports.create', 'uses' => 'ReportController@create']);
Route::put('reports/{reports}', ['as'=> 'reports.update', 'uses' => 'ReportController@update']);
Route::patch('reports/{reports}', ['as'=> 'reports.update', 'uses' => 'ReportController@update']);
Route::get('reports/{id}/delete', array('as' => 'reports.delete', 'uses' => 'ReportController@getDelete'));
Route::get('reports/{id}/confirm-delete', array('as' => 'reports.confirm-delete', 'uses' => 'ReportController@getModalDelete'));
Route::get('reports/{reports}', ['as'=> 'reports.show', 'uses' => 'ReportController@show']);
Route::get('reports/{reports}/edit', ['as'=> 'reports.edit', 'uses' => 'ReportController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('metadata', ['as'=> 'metadata.index', 'uses' => 'MetadataController@index']);
Route::post('metadata', ['as'=> 'metadata.store', 'uses' => 'MetadataController@store']);
Route::get('metadata/create', ['as'=> 'metadata.create', 'uses' => 'MetadataController@create']);
Route::put('metadata/{metadata}', ['as'=> 'metadata.update', 'uses' => 'MetadataController@update']);
Route::patch('metadata/{metadata}', ['as'=> 'metadata.update', 'uses' => 'MetadataController@update']);
Route::get('metadata/{id}/delete', array('as' => 'metadata.delete', 'uses' => 'MetadataController@getDelete'));
Route::get('metadata/{id}/confirm-delete', array('as' => 'metadata.confirm-delete', 'uses' => 'MetadataController@getModalDelete'));
Route::get('metadata/{metadata}', ['as'=> 'metadata.show', 'uses' => 'MetadataController@show']);
Route::get('metadata/{metadata}/edit', ['as'=> 'metadata.edit', 'uses' => 'MetadataController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('suppliers', ['as'=> 'suppliers.index', 'uses' => 'SupplierController@index']);
Route::post('suppliers', ['as'=> 'suppliers.store', 'uses' => 'SupplierController@store']);
Route::get('suppliers/create', ['as'=> 'suppliers.create', 'uses' => 'SupplierController@create']);
Route::put('suppliers/{suppliers}', ['as'=> 'suppliers.update', 'uses' => 'SupplierController@update']);
Route::patch('suppliers/{suppliers}', ['as'=> 'suppliers.update', 'uses' => 'SupplierController@update']);
Route::get('suppliers/{id}/delete', array('as' => 'suppliers.delete', 'uses' => 'SupplierController@getDelete'));
Route::get('suppliers/{id}/confirm-delete', array('as' => 'suppliers.confirm-delete', 'uses' => 'SupplierController@getModalDelete'));
Route::get('suppliers/{suppliers}', ['as'=> 'suppliers.show', 'uses' => 'SupplierController@show']);
Route::get('suppliers/{suppliers}/edit', ['as'=> 'suppliers.edit', 'uses' => 'SupplierController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('parts', ['as'=> 'parts.index', 'uses' => 'PartController@index']);
Route::post('parts', ['as'=> 'parts.store', 'uses' => 'PartController@store']);
Route::get('parts/create', ['as'=> 'parts.create', 'uses' => 'PartController@create']);
Route::put('parts/{parts}', ['as'=> 'parts.update', 'uses' => 'PartController@update']);
Route::patch('parts/{parts}', ['as'=> 'parts.update', 'uses' => 'PartController@update']);
Route::get('parts/{id}/delete', array('as' => 'parts.delete', 'uses' => 'PartController@getDelete'));
Route::get('parts/{id}/confirm-delete', array('as' => 'parts.confirm-delete', 'uses' => 'PartController@getModalDelete'));
Route::get('parts/{parts}', ['as'=> 'parts.show', 'uses' => 'PartController@show']);
Route::get('parts/{parts}/edit', ['as'=> 'parts.edit', 'uses' => 'PartController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('results', ['as'=> 'results.index', 'uses' => 'ResultController@index']);
Route::post('results', ['as'=> 'results.store', 'uses' => 'ResultController@store']);
Route::get('results/create', ['as'=> 'results.create', 'uses' => 'ResultController@create']);
Route::put('results/{results}', ['as'=> 'results.update', 'uses' => 'ResultController@update']);
Route::patch('results/{results}', ['as'=> 'results.update', 'uses' => 'ResultController@update']);
Route::get('results/{id}/delete', array('as' => 'results.delete', 'uses' => 'ResultController@getDelete'));
Route::get('results/{id}/confirm-delete', array('as' => 'results.confirm-delete', 'uses' => 'ResultController@getModalDelete'));
Route::get('results/{results}', ['as'=> 'results.show', 'uses' => 'ResultController@show']);
Route::get('results/{results}/edit', ['as'=> 'results.edit', 'uses' => 'ResultController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('labs', ['as'=> 'labs.index', 'uses' => 'LabController@index']);
Route::post('labs', ['as'=> 'labs.store', 'uses' => 'LabController@store']);
Route::get('labs/create', ['as'=> 'labs.create', 'uses' => 'LabController@create']);
Route::put('labs/{labs}', ['as'=> 'labs.update', 'uses' => 'LabController@update']);
Route::patch('labs/{labs}', ['as'=> 'labs.update', 'uses' => 'LabController@update']);
Route::get('labs/{id}/delete', array('as' => 'labs.delete', 'uses' => 'LabController@getDelete'));
Route::get('labs/{id}/confirm-delete', array('as' => 'labs.confirm-delete', 'uses' => 'LabController@getModalDelete'));
Route::get('labs/{labs}', ['as'=> 'labs.show', 'uses' => 'LabController@show']);
Route::get('labs/{labs}/edit', ['as'=> 'labs.edit', 'uses' => 'LabController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('contactLabs', ['as'=> 'contactLabs.index', 'uses' => 'ContactLabController@index']);
Route::post('contactLabs', ['as'=> 'contactLabs.store', 'uses' => 'ContactLabController@store']);
Route::get('contactLabs/create', ['as'=> 'contactLabs.create', 'uses' => 'ContactLabController@create']);
Route::put('contactLabs/{contactLabs}', ['as'=> 'contactLabs.update', 'uses' => 'ContactLabController@update']);
Route::patch('contactLabs/{contactLabs}', ['as'=> 'contactLabs.update', 'uses' => 'ContactLabController@update']);
Route::get('contactLabs/{id}/delete', array('as' => 'contactLabs.delete', 'uses' => 'ContactLabController@getDelete'));
Route::get('contactLabs/{id}/confirm-delete', array('as' => 'contactLabs.confirm-delete', 'uses' => 'ContactLabController@getModalDelete'));
Route::get('contactLabs/{contactLabs}', ['as'=> 'contactLabs.show', 'uses' => 'ContactLabController@show']);
Route::get('contactLabs/{contactLabs}/edit', ['as'=> 'contactLabs.edit', 'uses' => 'ContactLabController@edit']);

});
