<ul id="menu" class="page-sidebar-menu">

    <li {!! (Request::is('/') ? 'class="active"' : '') !!}>
        <a href="{{ route('admin.dashboard') }}">
            <i class="livicon" data-name="dashboard" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Dashboard 1</span>
        </a>
    </li>
<!--     <li {!! (Request::is('/index1') ? 'class="active"' : '') !!}>
        <a href="{{  URL::to('index1') }}">
            <i class="livicon" data-name="dashboard" data-size="18" data-c="#EF6F6C" data-hc="#EF6F6C"
               data-loop="true"></i>
            Dashboard 2
        </a>
    </li> -->

    <li {!! (Request::is('/generator_builder') ? 'class="active"' : '') !!}>
        <a href="{{ URL('generator_builder') }}">
            <i class="livicon" data-name="shield" data-size="18" data-c="#F89A14" data-hc="#F89A14"
               data-loop="true"></i>
            Generator Builder
        </a>
    </li>
    <li {!! (Request::is('/log_viewers') || Request::is('admin/log_viewers/logs')  ? 'class="active"' : '') !!}>

        <a href="{{  URL::to('log_viewers') }}">
            <i class="livicon" data-name="help" data-size="18" data-c="#1DA1F2" data-hc="#1DA1F2"
               data-loop="true"></i>
            Log Viewer
        </a>
    </li>
<!--     <li {!! (Request::is('/activity_log') ? 'class="active"' : '') !!}>
        <a href="{{  URL::to('activity_log') }}">
            <i class="livicon" data-name="eye-open" data-size="18" data-c="#F89A14" data-hc="#F89A14"
               data-loop="true"></i>
            Activity Log
        </a>
    </li> -->
    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>
